- name: register pyOpenSSL version
  command: python -c 'import OpenSSL; print(OpenSSL.__version__)'
  register: pyopenssl_version

- name: register openssl version
  shell: "openssl version | cut -d' ' -f2"
  register: openssl_version

- name: register cryptography version 2
  command: python -c 'import cryptography; print(cryptography.__version__)'
  register: cryptography_version
  when:
    - ansible_python_version is version('3.0', '<')

- name: register cryptography version 3
  command: python3 -c 'import cryptography; print(cryptography.__version__)'
  register: cryptography_version
  when:
    - ansible_python_version is version('3.0', '>=')
