---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=600
  when: ansible_os_family == 'Debian'

- name: Install openssl package dependencies
  ansible.builtin.package:
    name: '{{ openssl_packages }}'
    state: present
  become: true
  register: install_openssl_packages
  when: openssl_packages is defined
  tags:
    - install
    - apt
    - update_cache
