---
- name: Include vars by operating system.
  import_tasks: include_vars.yml

- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=600
  when: ansible_os_family == 'Debian'

- name: Install dependencies
  import_tasks: dependences.yml

- name: implement configure
  import_tasks: configure.yml

- name: Implement task install
  import_tasks: install.yml

- name: Implement task post install
  import_tasks: post_install.yml
